export const FREEBIE_LIST_REQUEST = 'FREEBIE_LIST_REQUEST'
export const FREEBIE_LIST_SUCCESS = 'FREEBIE_LIST_SUCCESS'
export const FREEBIE_LIST_FAIL = 'FREEBIE_LIST_FAIL'

export const FREEBIE_DETAILS_REQUEST = 'FREEBIE_DETAILS_REQUEST'
export const FREEBIE_DETAILS_SUCCESS = 'FREEBIE_DETAILS_SUCCESS'
export const FREEBIE_DETAILS_FAIL = 'FREEBIE_DETAILS_FAIL'