# Generated by Django 3.1.7 on 2022-01-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freebie',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
