# Generated by Django 3.1.7 on 2022-02-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_freebie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='freebie',
            name='countInStock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
